service: ansible-demo

provider:
  name: aws
  runtime: python3.6

functions:
  playbook:
    handler: playbook.handler
    events:
      - http:
          path: run
          method: get
    layers:
      - arn:aws:lambda:us-east-1:829846833214:layer:ansiblePython36:2

  hello:
    handler: hello.handler
    events:
      - http:
          path: hello
          method: get
